-- MySQL Script generated by MySQL Workbench
-- Currículo+ Database - Working...
-- Thu Sep 10 19:26:47 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema curriculo_mais_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curriculo_mais_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `curriculo_mais_db` ;

-- -----------------------------------------------------
-- Table `curriculo_mais_db`.`tbl_cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculo_mais_db`.`tbl_cidade` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curriculo_mais_db`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculo_mais_db`.`tbl_usuario` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `sobrenome` VARCHAR(75) NULL DEFAULT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` CHAR(64) NOT NULL,
  `is_rh` BOOLEAN NOT NULL DEFAULT 0 CHECK (`is_rh` BETWEEN 0 AND 1),
  `id_cidade` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_cidade` (`id_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_cidade`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `curriculo_mais_db`.`tbl_cidade` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curriculo_mais_db`.`tbl_vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculo_mais_db`.`tbl_vaga` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(75) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curriculo_mais_db`.`tbl_curriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculo_mais_db`.`tbl_curriculo` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `resumo_profissional` VARCHAR(200) NULL DEFAULT NULL,
  `curriculo` CHAR(31) NOT NULL,
  `data_envio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_ativo` TINYINT(1) NOT NULL DEFAULT '1',
  `id_usuario` SMALLINT UNSIGNED NOT NULL,
  `id_vaga` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_curriculo` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_vaga_curriculo` (`id_vaga` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_curriculo`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `curriculo_mais_db`.`tbl_usuario` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_vaga_curriculo`
    FOREIGN KEY (`id_vaga`)
    REFERENCES `curriculo_mais_db`.`tbl_vaga` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curriculo_mais_db`.`tbl_instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculo_mais_db`.`tbl_instituicao` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `id_cidade` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curriculo_mais_db`.`tbl_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculo_mais_db`.`tbl_telefone` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `telefone` CHAR(11) NOT NULL,
  `id_usuario` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `curriculo_mais_db`.`tbl_usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
